import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import MobileBar from './mobilebar'
import TopNav from './topNav'
import Footer from './footer'

export default function LandingPage({children}) {
    const [isDomLoaded, setIsDomLoaded] = useState(false)


    useEffect(() => {
        const timeout = setTimeout(() => {
            setIsDomLoaded(true)
        }, 3000)
        return () => {
            clearTimeout(timeout)
        }
    }, [])

    if(!isDomLoaded) {
        return <main className='bg-veryDeepBlue h-screen w-screen flex justify-center items-center'>
            <img src="assets/loading.gif" className='w-36 h-36' />
        </main>
    }

    if(isDomLoaded)  {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/assets/mainIcon.png" />
                </Head>
                <header>
                    <MobileBar />
                    <TopNav />
                </header>
                <main>
                    {children}
                </main>
                <footer>
                    <Footer />
                </footer>
            </>
        )
    }
}