import React, {useEffect, useState} from 'react';
import Head from 'next/head';

import MobileBar from './navs/mobilebar';
import TopNav from './navs/topNav';
import Footer from './footer';

export default function Layout({children}) {
    const [isDomLoaded, setIsDomLoaded] = useState(false);
    
    useEffect(() => {
        const timeout = setTimeout(() => {
            setIsDomLoaded(true)
        }, 1000)
        return () => {
            clearTimeout(timeout)
        }
    }, []);

    if(!isDomLoaded) {
        return <main className='bg-veryDeepBlue h-screen w-screen flex justify-center items-center'>
            <img src="assets/loading.gif" className='w-36 h-36' />
        </main>
    };

    if(isDomLoaded)  {
        return (
            <>
                <Head>
                    <title>Benax Collections</title>
                    <meta name="description" content="Generated by create next Nav" />
                    <link rel="icon" href="/assets/mainIcon.png" />
                </Head>
                <header>
                    <MobileBar />
                    <TopNav />
                </header>
                <main>
                    {children}
                </main>
                <footer>
                    <Footer />
                </footer>
            </>
        )
    };
}